name: tumdum_delivery_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  animated_marker: ^0.1.4
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_database: ^11.3.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_image_compress: ^2.4.0
  flutter_otp_text_field: ^1.4.0+2
  fluttertoast: ^8.2.10
  font_awesome_flutter: ^10.8.0
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  loader_overlay: ^5.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash/
