// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiG7zw7fWgZl8icc9yPLGNLtzcELThSuI',
    appId: '1:796930731185:android:af66a8f212c1766506c690',
    messagingSenderId: '796930731185',
    projectId: 'tumdum-delivery-app',
    storageBucket: 'tumdum-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXS8_RQWCOiLToUP0u8xZcndYUr_0A7o0',
    appId: '1:796930731185:ios:ebf8ef469017010506c690',
    messagingSenderId: '796930731185',
    projectId: 'tumdum-delivery-app',
    storageBucket: 'tumdum-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.tumdumDeliveryApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDZgfpJ4n2NObcRfRTbPdIp6JTXonvOwEE",
      authDomain: "tumdum-delivery-app.firebaseapp.com",
      projectId: "tumdum-delivery-app",
      storageBucket: "tumdum-delivery-app.firebasestorage.app",
      messagingSenderId: "796930731185",
      appId: "1:796930731185:web:08979d6b0bcc9a1406c690",
      measurementId: "G-5H6Q0P6ZE1");
}
